### ISSUE TITLE
please help 

### ISSUE THREAD

**Issue by gaurang1123** [ShafiqSadat/HamsterKeyGen#36]
I TRIED SINGLE AND MULTIPLE KEYS BUT KEEPS GIVING ERROR ALSO ON VPN

2024-08-21 20:03:56 | INFO     | 219 - Generating 1 key(s) for Riding Extreme 3D using proxies from proxy.txt
2024-08-21 20:03:56 | INFO     | 186 - Starting key generation for Riding Extreme 3D
Working... |2024-08-21 20:03:56 | INFO     | 146 - Generated client ID: 1724250836883-0472949001148232649
2024-08-21 20:03:56 | INFO     | 98 - Attempting to log in with client ID: 1724250836883-0472949001148232649 (Attempt 1/5)
Working... /2024-08-21 20:03:59 | ERROR    | 110 - Unexpected error during login (attempt 1/5): [Errno 11001] getaddrinfo failed
Working... \2024-08-21 20:04:01 | INFO     | 98 - Attempting to log in with client ID: 1724250836883-0472949001148232649 (Attempt 2/5)
Working... /2024-08-21 20:04:03 | ERROR    | 110 - Unexpected error during login (attempt 2/5): [Errno 11001] getaddrinfo failed
Working... \2024-08-21 20:04:05 | INFO     | 98 - Attempting to log in with client ID: 1724250836883-0472949001148232649 (Attempt 3/5)
Working... /2024-08-21 20:04:07 | ERROR    | 110 - Unexpected error during login (attempt 3/5): [Errno 11001] getaddrinfo failed
Working... \2024-08-21 20:04:09 | INFO     | 98 - Attempting to log in with client ID: 1724250836883-0472949001148232649 (Attempt 4/5)
Working... |2024-08-21 20:04:12 | ERROR    | 110 - Unexpected error during login (attempt 4/5): [Errno 11001] getaddrinfo failed
Working... \2024-08-21 20:04:14 | INFO     | 98 - Attempting to log in with client ID: 1724250836883-0472949001148232649 (Attempt 5/5)
Working... /2024-08-21 20:04:16 | ERROR    | 110 - Unexpected error during login (attempt 5/5): [Errno 11001] getaddrinfo failed
Working... \2024-08-21 20:04:18 | ERROR    | 112 - Maximum login attempts reached. Returning None.
2024-08-21 20:04:18 | ERROR    | 149 - Failed to generate client token for client ID: 1724250836883-0472949001148232649
2024-08-21 20:04:18 | INFO     | 205 - Key generation completed for Riding Extreme 3D
2024-08-21 20:04:18 | ERROR    | 231 - No keys were generated.
Press enter to exit

**Comment by ShafiqSadat** [comment]
The error `[Errno 11001] getaddrinfo failed` in Python usually occurs when the system is unable to resolve the hostname to an IP address. This can happen due to several reasons:

1. **Incorrect Hostname**: The hostname you are trying to connect to might be incorrect or misspelled.

2. **DNS Issues**: There might be an issue with the DNS server used by your system, preventing it from resolving the hostname.

3. **Network Issues**: If your internet connection is down or unstable, it could cause this error.

4. **Firewall or Security Software**: Sometimes, firewalls or security software can block DNS requests, leading to this error.

5. **Environment Configuration**: If you're working in a specific network environment (like a corporate network or VPN), there could be additional configurations or restrictions affecting DNS resolution.

### How to Troubleshoot:

1. **Check the Hostname**: Make sure the hostname you're trying to resolve is correct.

2. **Test DNS Resolution**: You can test DNS resolution by trying to ping the hostname from the command line or using tools like `nslookup` or `dig` to see if it resolves to an IP address.

3. **Check Internet Connection**: Ensure your system has a stable internet connection.

4. **Review Firewall/Security Settings**: Make sure no firewall or security software is blocking your DNS requests.

5. **Try a Different DNS Server**: You can configure your system to use a different DNS server, like Google's public DNS (8.8.8.8) or Cloudflare's (1.1.1.1), and see if that resolves the issue.

6. **Restart Your System**: Sometimes, simply restarting your system or network adapter can resolve transient network issues.

If you provide more context about the code or environment where this error is occurring, I can offer more specific advice.

**Comment by gaurang1123** [comment]
Thank you
